### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by Ryanzlay** [dangf15/THLNet#1]
def forward(self, x):
        skip = x
        for i in range(self.depth):
            out = getattr(self, 'pad{}'.format(i + 1))(skip)
            out = getattr(self, 'conv{}'.format(i + 1))(out)
            out = getattr(self, 'norm{}'.format(i + 1))(out)
            out = getattr(self, 'prelu{}'.format(i + 1))(out)
        return out
这里为啥每一层第一个都是skip，是不是相当于这个没用到呢，只用了最后一层？

**Comment by dangf15** [comment]
谢谢提醒，已修改对应代码。之后会整理更完整的脚本。
    def forward(self, x):
        skip = x
        for i in range(self.depth):
            out = getattr(self, 'pad{}'.format(i + 1))(skip)
            out = getattr(self, 'conv{}'.format(i + 1))(out)
            out = getattr(self, 'norm{}'.format(i + 1))(out)
            out= getattr(self, 'prelu{}'.format(i + 1))(out)
            skip = out
        return out

**Comment by Ryanzlay** [comment]
你好，请问你有dpcrn 的pytorh代码吗，想借鉴一下，自己没复现出来那种效果

**Comment by dangf15** [comment]
参考nets/dpcrn_block.py，改一下参数就可以了
